Add support for configuring with .netconfig
emgarten/Sleet pull request #128
Opened 2020-09-06 15:02 UTC by kzu

The [dotnetconfig](https://dotnetconfig.org) format allows hierarchical
tool settings to be persisted and read in a standards way by multiple
tools simultaneously. By adding this support to the tool, all settings
can now also be persisted to the`.netconfig` in the current directory
to streamline subsequent runs. In addition, for scenarios where multiple
projects/repositories in the local machine produce packages that are
pushed to the same feed(s), the `.netconfig` support makes it trivial
to reuse those settings across the entire machine by saving the settings
to the user profile instead.

Updated the docs to cover both `sleet.json` and `.netconfig` formats
equally.

2020-09-06 22:15 UTC, emgarten requested changes
This looks like a great way to handle configs, I would have used it from the start on sleet if it had existed then 😄 

CI is failing on the new unit tests, once everything is passing I'll be happy to take the PR.

2020-09-06 22:15 UTC, emgarten commented on test/SleetLib.Tests/ConfigTests.cs
> +        public void GivenItCanCanReadDotNetConfigVerifyJsonIsLoaded()
These tests are using env vars and running in parallel, which might be causing them to fail on the CI.

I would move these to Sleet.CmdExe.Tests where it runs Sleet.exe in a process with env vars only for that process.
https://github.com/emgarten/Sleet/blob/10b3c3d98a7626fb2244445b1ce789e059513c72/test/Sleet.CmdExe.Tests/DynamicSettingsTests.cs#L31

2020-09-06 22:15 UTC, emgarten commented on build/common/common.ps1
> +    $buildArgs += "/m:1"
👍 I was seeing some issues with concurrency also

2020-09-06 23:15 UTC, kzu commented on test/SleetLib.Tests/ConfigTests.cs
> +        public void GivenItCanCanReadDotNetConfigVerifyJsonIsLoaded()
Ahh, good point. Makes sense. I also removed in a subsequent commit the reliance on the envvars. Combined with the `/m:1` all problems went away.

2020-09-06 23:20 UTC, kzu commented
yay, all green!!!

2020-09-06 23:29 UTC, kzu commented
PR on dotnetconfig.org docs site pending this merge 👍 : https://github.com/dotnetconfig/dotnet-config/pull/14

2020-09-06 23:33 UTC, emgarten commented on test/SleetLib.Tests/ConfigTests.cs
> +            var path = Environment.GetEnvironmentVariable("SLEET_FEED_PATH");
this would still have issues running in parallel I believe, it should be tested in the exe tests where it is testing the other env var fallbacks

2020-09-06 23:40 UTC, kzu commented on test/SleetLib.Tests/ConfigTests.cs
> +            var path = Environment.GetEnvironmentVariable("SLEET_FEED_PATH");
but it no longer runs in parallel ;) (your +1 on the /m:1 change). Do you still think it's worth moving it?

2020-09-08 02:37 UTC, emgarten approved these changes
Thanks for the work on this @kzu :cake:

2020-09-08 02:38 UTC, merged